"Tropical_N_input_weed_control_rotation",
"Tropical_N_input_soil_cover_weed_control",
"Tropical_N_input_soil_cover_weed_control_rotation",
"Tropical_N_input_weed_control",
"Tropical_bt_all",
"Temperate_N_input_weed_control_rotation",
"Temperate_only weed_control",
"Temperate_N_input_weed_control",
"Temperate_N_input_soil_cover",
"Temperate_N_input_soil_cover_weed_control",
"Temperate_N_input_soil_cover_weed_control_rotation",
"Temperate_bt_all",
"Continental_only soil_cover",
"Continental_soil_cover_weed_control",
"Continental_N_input_weed_control_rotation",
"Continental_N_input_soil_cover_weed_control",
"Continental_N_input_soil_cover_weed_control_rotation",
"Continental_N_input_weed_control",
"Continental_bt_all",
"Arid_only weed_control",
"Arid_soil_cover_weed_control",
"Arid_N_input_weed_control",
"Arid_N_input_soil_cover",
"Arid_N_input_soil_cover_weed_control",
"Arid_N_input_soil_cover_weed_control_rotation",
"Arid_bt_all"

